:recycle: Improve overall UX
setopsco/docs pull request #30
Opened 2022-07-11 13:03 UTC by jonas612

2022-07-16 13:25 UTC, kevinscholz requested changes
Great that you are tackling this. The documentation indeed needs some improvements for first time users. I really like the new structure – makes it much easier to comprehend.

I added a few `Missing next step` comments. I think users should be able to follow the ready flow easily. Also I tried to fix/question some of the existing sections which are not quite clear or correct. Looking forward to your feedback.

2022-07-16 13:25 UTC, kevinscholz commented on content/latest/user/configuration/apps/container.md
> +```
Next step?

2022-07-16 13:25 UTC, kevinscholz commented on content/latest/user/configuration/apps/network.md
> +The Protocol determines how the App can be accessed from the outside. Like Scale, Protocol also is a mandatory parameter. Therefore, it can be modified by subsequently running the `network:set protoc
```suggestion
The Protocol determines how the App can be accessed via the network. Like Scale, Protocol also is a mandatory parameter. Therefore, it can be modified by subsequently running the `network:set protocol` command, but it can not be deleted from an App.
```

2022-07-16 13:25 UTC, kevinscholz commented on content/latest/user/configuration/apps/network.md
> +The Protocol value also determines how the App is reachable from the outside, and how it is checked for its health. The details are outlined in the table below.
```suggestion
The Protocol value also determines how the App is reachable from the outside (if Public is set to true), and how it is checked for its health. The details are outlined in the table below.
```

2022-07-16 13:25 UTC, kevinscholz commented on content/latest/user/configuration/apps/network.md
> +### Public
Move public up since Protocol strongly depends of on understanding of this section.

2022-07-16 13:25 UTC, kevinscholz commented on content/latest/user/configuration/apps/network.md
> +### Network Health Check
Only applicable if public is enabled

2022-07-16 13:25 UTC, kevinscholz commented on content/latest/user/configuration/apps/network.md
> +![App Checks schematic](checks.png)
Missing image

2022-07-16 13:25 UTC, kevinscholz commented on content/latest/user/configuration/apps/network.md
> +![App Checks schematic](checks.png)
Missing next step

2022-07-16 13:25 UTC, kevinscholz commented on content/latest/user/configuration/apps/resources.md
> +The Scale value determines how many instances of the App are to be running simultaneously. The default value for Scale is 1. You can specify an integer value between 0 and 16. A Scale value of 0 mean
```suggestion
The Scale value determines how many Tasks (containers) of the App are to be running simultaneously. The default value for Scale is 1. You can specify an integer value between 0 and 16. A Scale value of 0 means you do not want SetOps to run any container for this App. This may be useful to stop workers during deployments, for example.
```

2022-07-16 13:25 UTC, kevinscholz commented on content/latest/user/configuration/apps/resources.md
> +We recommend setting the `scale` for a web App to at least `2` for reliability reasons. The second container will be served in a different availability zone. That several zones are down at the same t
```suggestion
We recommend setting the `scale` for a web App to at least `2` for reliability reasons in production. The second container will be served in a different availability zone. That several zones are down at the same time is less likely. The application however must support that requests might be served by another instance.
```

2022-07-16 13:25 UTC, kevinscholz commented on content/latest/user/configuration/apps/resources.md
> +{{< /hint >}}
Missing next step

2022-07-16 13:25 UTC, kevinscholz commented on content/latest/user/configuration/apps/domains.md
> +{{< /hint >}}
Missing next step

2022-07-18 09:59 UTC, jonas612 commented on content/latest/user/configuration/apps/container.md
> +Every App has a command with which the container is started. If you don't set a command for an app, the default command specified in the *Dockerfile* (or in the upstream Docker image) is used. The co
To my knowledge the `container:set command` cmd expects the input to be in shell syntax. I corrected this part.

2022-07-18 11:18 UTC, jonas612 commented
@kevinscholz feel free to take another 👀

2022-07-21 07:50 UTC, kevinscholz commented on content/latest/user/configuration/apps/container.md
> +Every App has a command with which the container is started. If you don't set a command for an app, the default command specified in the *Dockerfile* (or in the upstream Docker image) is used. The co
I'd also propose to change `Docker` to container.

2022-07-21 07:54 UTC, kevinscholz commented on content/latest/user/configuration/apps/domains.md
> +[Create a service]({{< relref "/latest/user/configuration/services" >}}) for your new App.
In the menu, the next step would be `changesets`. Is there a reason that this links to service?

2022-08-16 09:13 UTC, jonas612 commented on content/latest/user/configuration/apps/domains.md
> +[Create a service]({{< relref "/latest/user/configuration/services" >}}) for your new App.
You are right, the menu was sorted incorrectly here.

2022-08-16 09:14 UTC, jonas612 commented
@kevinscholz this should be fine now 🚀

2022-08-16 09:21 UTC, kevinscholz approved these changes
Nice work 👏 Much cleaner now.

2022-08-16 09:21 UTC, merged